sudo: required
language: node_js
node_js:
  - "4.4.3"
install:
  - "npm install"
  - "npm install -g eslint eslint-config-airbnb eslint-plugin-react eslint-plugin-import stylelint mocha"
script:
  - "./scripts/tests.sh"
deploy:
  provider: script
  script: scripts/deploy.sh
  skip_cleanup: true
