sudo: required
language: node_js
node_js:
  - "4.4.3"
before_install:
  - "curl https://install.meteor.com | /bin/sh"
install:
  - "meteor npm install"
  - "npm install -g stylelint"
script:
  - "npm run lint"
  - "npm test"