sudo: required
language: node_js
node_js:
  - "4.4.3"
install:
  - "npm install"
  - "sudo pip install awscli"
script:
  - "./scripts/tests.sh"
after_success:
  - "./node_modules/.bin/nyc --require babel-core/register --reporter=text-lcov ./node_modules/.bin/mocha | ./node_modules/.bin/coveralls"
deploy:
  provider: script
  script: scripts/deploy.sh
  skip_cleanup: true
