sudo: required
language: node_js
node_js:
  - "4.4.3"
before_install:
  - "curl https://install.meteor.com | /bin/sh"
install:
  - "meteor npm install"
  - "npm install -g eslint eslint-config-airbnb eslint-plugin-react eslint-plugin-import"
  - "npm install -g stylelint"
script:
  - "eslint --ext js,jsx ."
  - "stylelint \"client/**/*.css\" \"imports/**/*.css\""
  - "npm test"