sudo: required
language: node_js
node_js:
  - "4.4.3"
install:
  - "npm install"
  - "sudo pip install awscli"
script:
  - "./scripts/tests.sh"
after_success:
  - "npm run coverage"
deploy:
  provider: script
  script: scripts/deploy.sh
  skip_cleanup: true
